Update UI components v2.0
tomstrong64/MyJourneyFootprint-COM617 pull request #51
Opened 2024-02-28 16:31 UTC by HamzaMohibe

Closed #48 
Remove some elements from the navbar and footer.
Change the icon of the website.
Update login and register page.
Add routes for each element

2024-02-28 17:39 UTC, tomstrong64 requested changes
Nice work, looks really good but there's a couple of things not displaying right on my system

2024-02-28 17:39 UTC, tomstrong64 commented on client/src/views/Calculate.vue
>        <div class="w-full sm:w-1/2 rounded-lg">
Seems to be an issue with alignment on larger screens, is this relating to the `sm:` part of the tailwind?
![image](https://github.com/tomstrong64/MyJourneyFootprint-COM617/assets/128226866/bea45c88-5cbd-4e39-8ea6-99adabcce628)

2024-02-28 17:39 UTC, tomstrong64 commented on client/src/components/AppFooter.vue
>                <i class="fab fa-facebook-square"></i>
Icons not displaying properly on mine
![image](https://github.com/tomstrong64/MyJourneyFootprint-COM617/assets/128226866/af0cea35-a4d4-43a9-9a21-190460244733)

2024-02-28 17:39 UTC, tomstrong64 commented on client/src/views/auth/Login.vue
> +              <h6 class="text-blueGray-500 text-sm font-bold">Sign in</h6>
Issues with colours on login page
![image](https://github.com/tomstrong64/MyJourneyFootprint-COM617/assets/128226866/cc4a2fc5-a27f-4b85-b50c-c28e1183ddd6)

Unsure what colours register is supposed to be, but just for reference this is what it looks like for me
![image](https://github.com/tomstrong64/MyJourneyFootprint-COM617/assets/128226866/9cc335ba-d91f-42b7-817b-20ccc7bc4adc)

2024-03-04 14:19 UTC, tomstrong64 approved these changes
LGTM, looks more consistent on my machine now, nice work

2024-03-04 14:23 UTC, AhubSajid approved these changes
Nice Work :)

2024-03-04 14:24 UTC, merged